# This file was generated by GoReleaser. DO NOT EDIT.
class Brodie < Formula
  desc "Brodie, the CLI"
  homepage "https://charm.sh/"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/charmbracelet/brodie/releases/download/v1.0.0/brodie_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "0bf0c7e849449072c4df607a4d4a7106320e5b87e1689537354ab45995467d48"
  elsif OS.linux?
  end

  def install
    bin.install "brodie"
  end
end
