# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Charm < Formula
  desc "The Charm Tool and Library 🌟"
  homepage "https://charm.sh/"
  version "0.10.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/charm/releases/download/v0.10.2/charm_0.10.2_Darwin_arm64.tar.gz"
      sha256 "5fe80656c7f36405395ddd8438b4ab022f627e63a237a6b874736da2d6b1e29b"

      def install
        bin.install "charm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/charm/releases/download/v0.10.2/charm_0.10.2_Darwin_x86_64.tar.gz"
      sha256 "289de58da1bffe3f97d231738b7a6c69327dcd391ec19d6637b68dca62e9d122"

      def install
        bin.install "charm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/charm/releases/download/v0.10.2/charm_0.10.2_linux_armv6.tar.gz"
      sha256 "7d4543d1e574e30f89a5f288d75848d4e73a768b1d3534d14d701767be8eceff"

      def install
        bin.install "charm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/charm/releases/download/v0.10.2/charm_0.10.2_linux_arm64.tar.gz"
      sha256 "7f4c59087fbd8df3c5a697b3e8767b49c48c89d8fa3fc35d3b1db3a5de71b9a9"

      def install
        bin.install "charm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/charm/releases/download/v0.10.2/charm_0.10.2_linux_x86_64.tar.gz"
      sha256 "3121cb451843ed6740881dbe6b28d26813d4775de39ae6c2effd3150b8577a80"

      def install
        bin.install "charm"
      end
    end
  end
end
