# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Confettysh < Formula
  desc "Confetty over SSH"
  homepage "https://charm.sh/"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/confettysh/releases/download/v1.0.1/confettysh_1.0.1_Darwin_arm64.tar.gz"
      sha256 "be7b6a6d1ed5fcddbef4a29280b1696c21c35e3e1f9ce09f4deab71fc6174a61"

      def install
        bin.install "confettysh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/confettysh/releases/download/v1.0.1/confettysh_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "baaecf9c729742872ab8f38e55cbb07cfaf33c9428b98a9c63a804c6475f072e"

      def install
        bin.install "confettysh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/confettysh/releases/download/v1.0.1/confettysh_1.0.1_linux_arm64.tar.gz"
      sha256 "51b04ac8bf2830c453306e897fffd4d7027f8856ee0a60f5825dabbb3c6164d8"

      def install
        bin.install "confettysh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/confettysh/releases/download/v1.0.1/confettysh_1.0.1_linux_x86_64.tar.gz"
      sha256 "25431dcf07f925db05747067dfdf6364ac840cfe8838866be88c685693ffef40"

      def install
        bin.install "confettysh"
      end
    end
  end
end
