# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Confettysh < Formula
  desc "Confetti over SSH"
  homepage "https://charm.sh/"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/confettysh/releases/download/v0.1.0/confettysh_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "9758c03d7c6d2a08967486176b5e4be00767be47121801ae16d83e17a6e6f979"

      def install
        bin.install "confettysh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/confettysh/releases/download/v0.1.0/confettysh_0.1.0_Darwin_arm64.tar.gz"
      sha256 "12d33bb8c89ec015e6e47be75941f012b972a879729e4bcd8f352e2728f61081"

      def install
        bin.install "confettysh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/confettysh/releases/download/v0.1.0/confettysh_0.1.0_linux_arm64.tar.gz"
      sha256 "4107daf287dd31721cbc30508f9cb70a0fc32e6e9f8741faaeb1b5f7b3fa9de0"

      def install
        bin.install "confettysh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/confettysh/releases/download/v0.1.0/confettysh_0.1.0_linux_x86_64.tar.gz"
      sha256 "04f29857ba2605cdb49f5fa41c6ab34ccd3b065443da3c20eeb2362ec312db95"

      def install
        bin.install "confettysh"
      end
    end
  end
end
