# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crush < Formula
  desc "A powerful terminal-based AI assistant for developers, providing intelligent coding assistance directly in your terminal."
  homepage "https://charm.sh/crush"
  version "0.7.0"
  license "FSL-1.1-MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/crush/releases/download/v0.7.0/crush_0.7.0_Darwin_x86_64.tar.gz"
      sha256 "540309d78475e119888a7035b1b98a0ce00b07715b8de31761caa73103962e66"

      def install
        bin.install "crush"
        bash_completion.install "completions/crush.bash" => "crush"
        zsh_completion.install "completions/crush.zsh" => "_crush"
        fish_completion.install "completions/crush.fish"
        man1.install "manpages/crush.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/crush/releases/download/v0.7.0/crush_0.7.0_Darwin_arm64.tar.gz"
      sha256 "75698e75e6c68190612f791f85d9ab0ad5627286fdc0c1d6b4f954ed1d0abf85"

      def install
        bin.install "crush"
        bash_completion.install "completions/crush.bash" => "crush"
        zsh_completion.install "completions/crush.zsh" => "_crush"
        fish_completion.install "completions/crush.fish"
        man1.install "manpages/crush.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/crush/releases/download/v0.7.0/crush_0.7.0_Linux_x86_64.tar.gz"
      sha256 "c3c14873f730c530dd9c656bf2b8851d4d3666d44ed36b8c94e0243951060c2f"
      def install
        bin.install "crush"
        bash_completion.install "completions/crush.bash" => "crush"
        zsh_completion.install "completions/crush.zsh" => "_crush"
        fish_completion.install "completions/crush.fish"
        man1.install "manpages/crush.1.gz"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/crush/releases/download/v0.7.0/crush_0.7.0_Linux_armv7.tar.gz"
      sha256 "5ab8ad376b7eeb40d4cb13e9f346f9355f4b1c7d34c9807e25ba6a31df18ba26"
      def install
        bin.install "crush"
        bash_completion.install "completions/crush.bash" => "crush"
        zsh_completion.install "completions/crush.zsh" => "_crush"
        fish_completion.install "completions/crush.fish"
        man1.install "manpages/crush.1.gz"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/crush/releases/download/v0.7.0/crush_0.7.0_Linux_arm64.tar.gz"
      sha256 "94b544725db31d4ed923ed1107bab6373c255b0417240f73d75ab75131c8d03b"
      def install
        bin.install "crush"
        bash_completion.install "completions/crush.bash" => "crush"
        zsh_completion.install "completions/crush.zsh" => "_crush"
        fish_completion.install "completions/crush.fish"
        man1.install "manpages/crush.1.gz"
      end
    end
  end
end
