# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Freeze < Formula
  desc "Generate images of code and terminal output."
  homepage "https://charm.sh/"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/freeze/releases/download/v0.2.0/freeze_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "a0e55ac142196430d279fb27dbbe82ae912c301be1783540a036b81e36f9f802"

      def install
        bin.install "freeze"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/freeze/releases/download/v0.2.0/freeze_0.2.0_Darwin_arm64.tar.gz"
      sha256 "f6e0e94ab63bca307643fb1fd881e1f16a035e7bf8c4ff7e55baaed3af15ebf1"

      def install
        bin.install "freeze"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/freeze/releases/download/v0.2.0/freeze_0.2.0_Linux_x86_64.tar.gz"
        sha256 "c0acfbc00c30e3849d3f1aa49f40fbf630b89cc96ce6b436f7844bf5533c10d1"

        def install
          bin.install "freeze"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/freeze/releases/download/v0.2.0/freeze_0.2.0_Linux_arm64.tar.gz"
        sha256 "1f0052301c8cf1adbb79c3ad5e420d382e85751531a919284c7b9b484eb528f0"

        def install
          bin.install "freeze"
        end
      end
    end
  end
end
