# This file was generated by GoReleaser. DO NOT EDIT.
class Glow < Formula
  desc "Render markdown on the CLI"
  homepage "https://charm.sh/"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/charmbracelet/glow/releases/download/v0.2.0/glow_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "31ca9403ffb63fa653b097c1440e1dc1e1186911ad209668b84528680896b844"
  elsif OS.linux?
  end

  def install
    bin.install "glow"
  end
end
