# This file was generated by GoReleaser. DO NOT EDIT.
class Glow < Formula
  desc "Render markdown on the CLI"
  homepage "https://charm.sh/"
  version "0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/charmbracelet/glow/releases/download/v0.1/glow_0.1_Darwin_x86_64.tar.gz"
    sha256 "60e3ed041a759c7db6d3f9dd4730ddb02fb9d99b9366785385870cfba942f939"
  elsif OS.linux?
  end

  def install
    bin.install "glow"
  end
end
