# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gum < Formula
  desc "A tool for glamorous shell scripts"
  homepage "https://charm.sh/"
  version "0.14.1"

  on_macos do
    on_intel do
      url "https://github.com/charmbracelet/gum/releases/download/v0.14.1/gum_0.14.1_Darwin_x86_64.tar.gz"
      sha256 "f89fcad1157ad093c58659008b0fe6f61e3ff913a7af4bbc0873df9a593c5a08"

      def install
        bin.install "gum"
        bash_completion.install "completions/gum.bash" => "gum"
        zsh_completion.install "completions/gum.zsh" => "_gum"
        fish_completion.install "completions/gum.fish"
        man1.install "manpages/gum.1.gz"
      end
    end
    on_arm do
      url "https://github.com/charmbracelet/gum/releases/download/v0.14.1/gum_0.14.1_Darwin_arm64.tar.gz"
      sha256 "617c99becb818bdc87d627b779dbad9c09d0b605da8abdf63098f4deebc2f006"

      def install
        bin.install "gum"
        bash_completion.install "completions/gum.bash" => "gum"
        zsh_completion.install "completions/gum.zsh" => "_gum"
        fish_completion.install "completions/gum.fish"
        man1.install "manpages/gum.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/gum/releases/download/v0.14.1/gum_0.14.1_Linux_x86_64.tar.gz"
        sha256 "7b267e7555a5c5a5ae56aafddcb9065abd915b098a864674f8559963b6cc0a9f"

        def install
          bin.install "gum"
          bash_completion.install "completions/gum.bash" => "gum"
          zsh_completion.install "completions/gum.zsh" => "_gum"
          fish_completion.install "completions/gum.fish"
          man1.install "manpages/gum.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/gum/releases/download/v0.14.1/gum_0.14.1_Linux_armv7.tar.gz"
        sha256 "53b26259ed57db0cbb45c2d7e599b1e96fbfe787e930eff0a8266a49ddbc06e3"

        def install
          bin.install "gum"
          bash_completion.install "completions/gum.bash" => "gum"
          zsh_completion.install "completions/gum.zsh" => "_gum"
          fish_completion.install "completions/gum.fish"
          man1.install "manpages/gum.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/gum/releases/download/v0.14.1/gum_0.14.1_Linux_arm64.tar.gz"
        sha256 "21222f1059d72bc962d013a05f241110b7b32ba321a58ecb5ed351feace61933"

        def install
          bin.install "gum"
          bash_completion.install "completions/gum.bash" => "gum"
          zsh_completion.install "completions/gum.zsh" => "_gum"
          fish_completion.install "completions/gum.fish"
          man1.install "manpages/gum.1.gz"
        end
      end
    end
  end
end
