# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gum < Formula
  desc "A tool for glamorous shell scripts"
  homepage "https://charm.sh/"
  version "0.14.4"

  on_macos do
    on_intel do
      url "https://github.com/charmbracelet/gum/releases/download/v0.14.4/gum_0.14.4_Darwin_x86_64.tar.gz"
      sha256 "300ba50a52eba5ff2bae3124b4818ecd6e4946cb62f5859f51d059300358e0eb"

      def install
        bin.install "gum"
        bash_completion.install "completions/gum.bash" => "gum"
        zsh_completion.install "completions/gum.zsh" => "_gum"
        fish_completion.install "completions/gum.fish"
        man1.install "manpages/gum.1.gz"
      end
    end
    on_arm do
      url "https://github.com/charmbracelet/gum/releases/download/v0.14.4/gum_0.14.4_Darwin_arm64.tar.gz"
      sha256 "a0a7867f2bd4c61ecd97faeb2cb9e0a4eef2ec4c09a69d43cc8fca3b8df7a698"

      def install
        bin.install "gum"
        bash_completion.install "completions/gum.bash" => "gum"
        zsh_completion.install "completions/gum.zsh" => "_gum"
        fish_completion.install "completions/gum.fish"
        man1.install "manpages/gum.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/gum/releases/download/v0.14.4/gum_0.14.4_Linux_x86_64.tar.gz"
        sha256 "617914431e20473fd6b097b123b2e0dedaba8a9d2ae9fb59eaeb4206a95c3381"

        def install
          bin.install "gum"
          bash_completion.install "completions/gum.bash" => "gum"
          zsh_completion.install "completions/gum.zsh" => "_gum"
          fish_completion.install "completions/gum.fish"
          man1.install "manpages/gum.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/gum/releases/download/v0.14.4/gum_0.14.4_Linux_armv7.tar.gz"
        sha256 "561e6709e5f4e623389b211df2bee979bcdde71f535a5e16f776a46fb72c5015"

        def install
          bin.install "gum"
          bash_completion.install "completions/gum.bash" => "gum"
          zsh_completion.install "completions/gum.zsh" => "_gum"
          fish_completion.install "completions/gum.fish"
          man1.install "manpages/gum.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/gum/releases/download/v0.14.4/gum_0.14.4_Linux_arm64.tar.gz"
        sha256 "4f937eb8e06c4903ce4a2a0d6a274afbcba77fd13bea2f648c613ec2e3d1a2da"

        def install
          bin.install "gum"
          bash_completion.install "completions/gum.bash" => "gum"
          zsh_completion.install "completions/gum.zsh" => "_gum"
          fish_completion.install "completions/gum.fish"
          man1.install "manpages/gum.1.gz"
        end
      end
    end
  end
end
