# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gum < Formula
  desc "A tool for glamorous shell scripts"
  homepage "https://charm.sh/"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/gum/releases/download/v0.7.0/gum_0.7.0_Darwin_arm64.tar.gz"
      sha256 "73b4f958b2a94a30bcb952740102ae6df6571a792491702e7f0fd098ed5b316b"

      def install
        bin.install "gum"
        bash_completion.install "completions/gum.bash" => "gum"
        zsh_completion.install "completions/gum.zsh" => "_gum"
        fish_completion.install "completions/gum.fish"
        man1.install "manpages/gum.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/gum/releases/download/v0.7.0/gum_0.7.0_Darwin_x86_64.tar.gz"
      sha256 "a8bb8ccab7cb1b06a69e2d142cf4b066d3c9658999b7fc9d58391dc9d88e8e33"

      def install
        bin.install "gum"
        bash_completion.install "completions/gum.bash" => "gum"
        zsh_completion.install "completions/gum.zsh" => "_gum"
        fish_completion.install "completions/gum.fish"
        man1.install "manpages/gum.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/gum/releases/download/v0.7.0/gum_0.7.0_linux_x86_64.tar.gz"
      sha256 "60bf431f2015e6d93556171c1529d03f5abd55d34aa69a1f82d8f38ad9f23244"

      def install
        bin.install "gum"
        bash_completion.install "completions/gum.bash" => "gum"
        zsh_completion.install "completions/gum.zsh" => "_gum"
        fish_completion.install "completions/gum.fish"
        man1.install "manpages/gum.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/gum/releases/download/v0.7.0/gum_0.7.0_linux_arm64.tar.gz"
      sha256 "dba67cd9393f1061c0492fdaabf3db639627b0b52c78066711aa4cd0a1442451"

      def install
        bin.install "gum"
        bash_completion.install "completions/gum.bash" => "gum"
        zsh_completion.install "completions/gum.zsh" => "_gum"
        fish_completion.install "completions/gum.fish"
        man1.install "manpages/gum.1.gz"
      end
    end
  end
end
