# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Markscribe < Formula
  desc "Your personal markdown scribe with template-engine and Git(Hub) & RSS powers"
  homepage "https://charm.sh/"
  version "0.7.2"

  on_macos do
    on_intel do
      url "https://github.com/charmbracelet/markscribe/releases/download/v0.7.2/markscribe_0.7.2_Darwin_x86_64.tar.gz"
      sha256 "05eb176b74169e9658a321067a41eb54de6744f2a3e2ac4683e787cf4ea61bf7"

      def install
        bin.install "markscribe"
      end
    end
    on_arm do
      url "https://github.com/charmbracelet/markscribe/releases/download/v0.7.2/markscribe_0.7.2_Darwin_arm64.tar.gz"
      sha256 "39b15cdbb2b07a0659c0508c2d3f3439eb177f44436413cae1e09979442794c0"

      def install
        bin.install "markscribe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/markscribe/releases/download/v0.7.2/markscribe_0.7.2_Linux_x86_64.tar.gz"
        sha256 "b7ec74a14b9a4e5645cee32739852f6c986b20392575ddbb0cfe2d7302cf433c"

        def install
          bin.install "markscribe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/markscribe/releases/download/v0.7.2/markscribe_0.7.2_Linux_arm64.tar.gz"
        sha256 "73f809ef35519189cf40034244c0d34596c8b7500eecc92c567f7224affd42c6"

        def install
          bin.install "markscribe"
        end
      end
    end
  end
end
