# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Markscribe < Formula
  desc "Your personal markdown scribe with template-engine and Git(Hub) & RSS powers"
  homepage "https://charm.sh/"
  version "0.7.1"

  on_macos do
    on_intel do
      url "https://github.com/charmbracelet/markscribe/releases/download/v0.7.1/markscribe_0.7.1_Darwin_x86_64.tar.gz"
      sha256 "5cbf2cd1e6877b4e9aa28f96beaae92cc896afb4fd8ad7161378a0b7391e5975"

      def install
        bin.install "markscribe"
      end
    end
    on_arm do
      url "https://github.com/charmbracelet/markscribe/releases/download/v0.7.1/markscribe_0.7.1_Darwin_arm64.tar.gz"
      sha256 "1849b4f2046ff1f84c7f306d8393682cdc5457dfeba4f8ed4ab04b946a6fc3d7"

      def install
        bin.install "markscribe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/markscribe/releases/download/v0.7.1/markscribe_0.7.1_Linux_x86_64.tar.gz"
        sha256 "36387775a0aaee9a159dbd6c1f2a464ea668967a9816deeab667b1313e794640"

        def install
          bin.install "markscribe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/markscribe/releases/download/v0.7.1/markscribe_0.7.1_Linux_arm64.tar.gz"
        sha256 "9bae493f346e85c7e114f227f1d2a1753f65293a2e6e565fb8d4504d39e1d21c"

        def install
          bin.install "markscribe"
        end
      end
    end
  end
end
