# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Melt < Formula
  desc "Backup and restore SSH keys as mnemonic set of words"
  homepage "https://charm.sh/"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/melt/releases/download/v0.2.0/melt_0.2.0_Darwin_arm64.tar.gz"
      sha256 "6a8974ba96b101fd16a0590fb707dde15aeb438b166b49490e2ad94f7a1414d1"

      def install
        bin.install "melt"
        bash_completion.install "completions/melt.bash" => "melt"
        zsh_completion.install "completions/melt.zsh" => "_melt"
        fish_completion.install "completions/melt.fish"
        man1.install "manpages/melt.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/melt/releases/download/v0.2.0/melt_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "44bfc45051d99efe854256b5b5c2fa9d2ae5642097d7042c8b5ea8d4fa63720b"

      def install
        bin.install "melt"
        bash_completion.install "completions/melt.bash" => "melt"
        zsh_completion.install "completions/melt.zsh" => "_melt"
        fish_completion.install "completions/melt.fish"
        man1.install "manpages/melt.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/melt/releases/download/v0.2.0/melt_0.2.0_linux_x86_64.tar.gz"
      sha256 "01662bec3bf8cc3f384a00fd4b90c21412415088a34221879e767297fb492120"

      def install
        bin.install "melt"
        bash_completion.install "completions/melt.bash" => "melt"
        zsh_completion.install "completions/melt.zsh" => "_melt"
        fish_completion.install "completions/melt.fish"
        man1.install "manpages/melt.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/melt/releases/download/v0.2.0/melt_0.2.0_linux_arm64.tar.gz"
      sha256 "e37c55f5cfc95daf953b119270f1d7f04478bdffe69f2faa8c3ff227aa8950a0"

      def install
        bin.install "melt"
        bash_completion.install "completions/melt.bash" => "melt"
        zsh_completion.install "completions/melt.zsh" => "_melt"
        fish_completion.install "completions/melt.fish"
        man1.install "manpages/melt.1.gz"
      end
    end
  end
end
