# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Melt < Formula
  desc "Backup and restore Ed25519 SSH keys with seed words"
  homepage "https://charm.sh/"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/melt/releases/download/v0.4.1/melt_0.4.1_Darwin_x86_64.tar.gz"
      sha256 "383ae9761f6a822e6e56f04035000abf8e08531e032e4574eef4941de145b10c"

      def install
        bin.install "melt"
        bash_completion.install "completions/melt.bash" => "melt"
        zsh_completion.install "completions/melt.zsh" => "_melt"
        fish_completion.install "completions/melt.fish"
        man1.install "manpages/melt.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/melt/releases/download/v0.4.1/melt_0.4.1_Darwin_arm64.tar.gz"
      sha256 "1dc93ea4e3a2b6fa743ccf2ffd8da5871b9ff6704a68fde594a56992da5e4e8e"

      def install
        bin.install "melt"
        bash_completion.install "completions/melt.bash" => "melt"
        zsh_completion.install "completions/melt.zsh" => "_melt"
        fish_completion.install "completions/melt.fish"
        man1.install "manpages/melt.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/melt/releases/download/v0.4.1/melt_0.4.1_linux_x86_64.tar.gz"
      sha256 "f98510b21e88be9284312e83d8d1e893f52172015afc08fa7ec221fb9ad89ef2"

      def install
        bin.install "melt"
        bash_completion.install "completions/melt.bash" => "melt"
        zsh_completion.install "completions/melt.zsh" => "_melt"
        fish_completion.install "completions/melt.fish"
        man1.install "manpages/melt.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/melt/releases/download/v0.4.1/melt_0.4.1_linux_arm64.tar.gz"
      sha256 "85c65739858302aeded4809f008528a2bbbb8efd37f3c874dff2111968dedd4c"

      def install
        bin.install "melt"
        bash_completion.install "completions/melt.bash" => "melt"
        zsh_completion.install "completions/melt.zsh" => "_melt"
        fish_completion.install "completions/melt.fish"
        man1.install "manpages/melt.1.gz"
      end
    end
  end
end
