# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mods < Formula
  desc "AI on the command line"
  homepage "https://charm.sh/"
  version "1.6.0"

  on_macos do
    on_intel do
      url "https://github.com/charmbracelet/mods/releases/download/v1.6.0/mods_1.6.0_Darwin_x86_64.tar.gz"
      sha256 "86043c5e4d032bc0d212db4137555328be07e779428a6ff5d0ffaaab9b4871d9"

      def install
        bin.install "mods"
        bash_completion.install "completions/mods.bash" => "mods"
        zsh_completion.install "completions/mods.zsh" => "_mods"
        fish_completion.install "completions/mods.fish"
        man1.install "manpages/mods.1.gz"
      end
    end
    on_arm do
      url "https://github.com/charmbracelet/mods/releases/download/v1.6.0/mods_1.6.0_Darwin_arm64.tar.gz"
      sha256 "e412849e94a2492889eb309fcf778b9f7a1c77e78af203b51057d7cd02677661"

      def install
        bin.install "mods"
        bash_completion.install "completions/mods.bash" => "mods"
        zsh_completion.install "completions/mods.zsh" => "_mods"
        fish_completion.install "completions/mods.fish"
        man1.install "manpages/mods.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/mods/releases/download/v1.6.0/mods_1.6.0_Linux_x86_64.tar.gz"
        sha256 "b034e5d6b8b5703a5eb54eb1854c856502506e7d1fbdb206435b56b65a2c2310"

        def install
          bin.install "mods"
          bash_completion.install "completions/mods.bash" => "mods"
          zsh_completion.install "completions/mods.zsh" => "_mods"
          fish_completion.install "completions/mods.fish"
          man1.install "manpages/mods.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/mods/releases/download/v1.6.0/mods_1.6.0_Linux_arm64.tar.gz"
        sha256 "33c14a3b38f13997a4c4c6106672196b062433892f5393dc372f359ed73c0e8b"

        def install
          bin.install "mods"
          bash_completion.install "completions/mods.bash" => "mods"
          zsh_completion.install "completions/mods.zsh" => "_mods"
          fish_completion.install "completions/mods.fish"
          man1.install "manpages/mods.1.gz"
        end
      end
    end
  end
end
