# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mods < Formula
  desc "AI on the command line"
  homepage "https://charm.sh/"
  version "1.5.0"

  on_macos do
    on_intel do
      url "https://github.com/charmbracelet/mods/releases/download/v1.5.0/mods_1.5.0_Darwin_x86_64.tar.gz"
      sha256 "6d6e571ffa9c3c94f2e2376794ecb8be07328807497e8ed0c344d2baac9fad4e"

      def install
        bin.install "mods"
        bash_completion.install "completions/mods.bash" => "mods"
        zsh_completion.install "completions/mods.zsh" => "_mods"
        fish_completion.install "completions/mods.fish"
        man1.install "manpages/mods.1.gz"
      end
    end
    on_arm do
      url "https://github.com/charmbracelet/mods/releases/download/v1.5.0/mods_1.5.0_Darwin_arm64.tar.gz"
      sha256 "89aae6b45d67031d93dfee56b0e4c5a117e9a8889854682600e8d706774a8ec4"

      def install
        bin.install "mods"
        bash_completion.install "completions/mods.bash" => "mods"
        zsh_completion.install "completions/mods.zsh" => "_mods"
        fish_completion.install "completions/mods.fish"
        man1.install "manpages/mods.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/mods/releases/download/v1.5.0/mods_1.5.0_Linux_x86_64.tar.gz"
        sha256 "608e2e3a440e26b394857151845a9eac70fb9204796814e9866f5953ed7d83f6"

        def install
          bin.install "mods"
          bash_completion.install "completions/mods.bash" => "mods"
          zsh_completion.install "completions/mods.zsh" => "_mods"
          fish_completion.install "completions/mods.fish"
          man1.install "manpages/mods.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/mods/releases/download/v1.5.0/mods_1.5.0_Linux_arm64.tar.gz"
        sha256 "8cc9383f5c42efb5dea1305095ae85e38281a1c86a4cabfb461ba99647236333"

        def install
          bin.install "mods"
          bash_completion.install "completions/mods.bash" => "mods"
          zsh_completion.install "completions/mods.zsh" => "_mods"
          fish_completion.install "completions/mods.fish"
          man1.install "manpages/mods.1.gz"
        end
      end
    end
  end
end
