# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mods < Formula
  desc "AI on the command line"
  homepage "https://charm.sh/"
  version "1.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/mods/releases/download/v1.8.1/mods_1.8.1_Darwin_x86_64.tar.gz"
      sha256 "0ae5f55ae1764fd47c347a7b4e75b71dbcdbb41e56c64bf90be4f1481dba0377"

      def install
        bin.install "mods"
        bash_completion.install "completions/mods.bash" => "mods"
        zsh_completion.install "completions/mods.zsh" => "_mods"
        fish_completion.install "completions/mods.fish"
        man1.install "manpages/mods.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/mods/releases/download/v1.8.1/mods_1.8.1_Darwin_arm64.tar.gz"
      sha256 "a09528a438487fbda43809d5adcbc4211a5020bd69372ff0d319a8f28bd900b2"

      def install
        bin.install "mods"
        bash_completion.install "completions/mods.bash" => "mods"
        zsh_completion.install "completions/mods.zsh" => "_mods"
        fish_completion.install "completions/mods.fish"
        man1.install "manpages/mods.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/mods/releases/download/v1.8.1/mods_1.8.1_Linux_x86_64.tar.gz"
      sha256 "a3313f3064f7c104835e1f9c53788524cfafc1675c1e18fca786b7051766745d"
      def install
        bin.install "mods"
        bash_completion.install "completions/mods.bash" => "mods"
        zsh_completion.install "completions/mods.zsh" => "_mods"
        fish_completion.install "completions/mods.fish"
        man1.install "manpages/mods.1.gz"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/mods/releases/download/v1.8.1/mods_1.8.1_Linux_arm64.tar.gz"
      sha256 "448d205e27e1ec0cb4e185275ff826e93b16182d35977652db01e4d475b1b671"
      def install
        bin.install "mods"
        bash_completion.install "completions/mods.bash" => "mods"
        zsh_completion.install "completions/mods.zsh" => "_mods"
        fish_completion.install "completions/mods.fish"
        man1.install "manpages/mods.1.gz"
      end
    end
  end
end
