# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pop < Formula
  desc "Send emails from your terminal. 📬"
  homepage "https://charm.land/"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/pop/releases/download/v0.2.2/pop_0.2.2_Darwin_x86_64.tar.gz"
      sha256 "0a58c0669ab6a53185bc8061ba82eb1aed497702c97672c5117290df7ef33d31"

      define_method(:install) do
        bin.install "pop"
        bash_completion.install "completions/pop.bash" => "pop"
        zsh_completion.install "completions/pop.zsh" => "_pop"
        fish_completion.install "completions/pop.fish"
        man1.install "manpages/pop.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/pop/releases/download/v0.2.2/pop_0.2.2_Darwin_arm64.tar.gz"
      sha256 "940d7ae189274dbbf43c29075401e4af6ebf682800dd0e16434768426d5c33c8"

      define_method(:install) do
        bin.install "pop"
        bash_completion.install "completions/pop.bash" => "pop"
        zsh_completion.install "completions/pop.zsh" => "_pop"
        fish_completion.install "completions/pop.fish"
        man1.install "manpages/pop.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/pop/releases/download/v0.2.2/pop_0.2.2_Linux_x86_64.tar.gz"
      sha256 "6ef74756f90c66be703152079598010ee458920fe663dbf44f0e9eb8394e938c"
      define_method(:install) do
        bin.install "pop"
        bash_completion.install "completions/pop.bash" => "pop"
        zsh_completion.install "completions/pop.zsh" => "_pop"
        fish_completion.install "completions/pop.fish"
        man1.install "manpages/pop.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/pop/releases/download/v0.2.2/pop_0.2.2_Linux_armv7.tar.gz"
      sha256 "f1e6cc2d3aa6cf9187f34b2b0076b98fbd6d588b918924657f95db5a675a8b20"
      define_method(:install) do
        bin.install "pop"
        bash_completion.install "completions/pop.bash" => "pop"
        zsh_completion.install "completions/pop.zsh" => "_pop"
        fish_completion.install "completions/pop.fish"
        man1.install "manpages/pop.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/pop/releases/download/v0.2.2/pop_0.2.2_Linux_arm64.tar.gz"
      sha256 "4ca3a46730ba8a59eacbab76feb1a2abe2436759b65946b0c09c8e5cb20671fd"
      define_method(:install) do
        bin.install "pop"
        bash_completion.install "completions/pop.bash" => "pop"
        zsh_completion.install "completions/pop.zsh" => "_pop"
        fish_completion.install "completions/pop.fish"
        man1.install "manpages/pop.1.gz"
      end
    end
  end
end
