# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pop < Formula
  desc "Send emails from your terminal. 📬"
  homepage "https://charm.land/"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/pop/releases/download/v0.4.0/pop_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "35d83fbb097c3cc23ca23b053a786b9a3825be5346fd76f304e8d80002983a67"

      define_method(:install) do
        bin.install "pop"
        bash_completion.install "completions/pop.bash" => "pop"
        zsh_completion.install "completions/pop.zsh" => "_pop"
        fish_completion.install "completions/pop.fish"
        man1.install "manpages/pop.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/pop/releases/download/v0.4.0/pop_0.4.0_Darwin_arm64.tar.gz"
      sha256 "e9c67e011292b924f13c9a577e0cb2fc81d0e952663a626f42a7f7a6a3be83a2"

      define_method(:install) do
        bin.install "pop"
        bash_completion.install "completions/pop.bash" => "pop"
        zsh_completion.install "completions/pop.zsh" => "_pop"
        fish_completion.install "completions/pop.fish"
        man1.install "manpages/pop.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/pop/releases/download/v0.4.0/pop_0.4.0_Linux_x86_64.tar.gz"
      sha256 "3d62475f0b295f601f01a7d8bb3f0aded0966dcc195b589eb88fc09df68b48f5"
      define_method(:install) do
        bin.install "pop"
        bash_completion.install "completions/pop.bash" => "pop"
        zsh_completion.install "completions/pop.zsh" => "_pop"
        fish_completion.install "completions/pop.fish"
        man1.install "manpages/pop.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/pop/releases/download/v0.4.0/pop_0.4.0_Linux_armv7.tar.gz"
      sha256 "4bfd95a289d123b1665544c1b94d23f9022d41c2736cbaa7955a95dbed312a10"
      define_method(:install) do
        bin.install "pop"
        bash_completion.install "completions/pop.bash" => "pop"
        zsh_completion.install "completions/pop.zsh" => "_pop"
        fish_completion.install "completions/pop.fish"
        man1.install "manpages/pop.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/pop/releases/download/v0.4.0/pop_0.4.0_Linux_arm64.tar.gz"
      sha256 "e1fadfc38dc5c5ad28064fec9f566be3324771f4933b0bbb4dc8524bab39b6ba"
      define_method(:install) do
        bin.install "pop"
        bash_completion.install "completions/pop.bash" => "pop"
        zsh_completion.install "completions/pop.zsh" => "_pop"
        fish_completion.install "completions/pop.fish"
        man1.install "manpages/pop.1.gz"
      end
    end
  end
end
