# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pop < Formula
  desc "Send emails from your terminal. 📬"
  homepage "https://charm.land/"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/pop/releases/download/v0.5.0/pop_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "108dae3baad6610015ae523d26ab08a27d3d6993de9335549c1c13aabc2ca247"

      define_method(:install) do
        bin.install "pop"
        bash_completion.install "completions/pop.bash" => "pop"
        zsh_completion.install "completions/pop.zsh" => "_pop"
        fish_completion.install "completions/pop.fish"
        man1.install "manpages/pop.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/pop/releases/download/v0.5.0/pop_0.5.0_Darwin_arm64.tar.gz"
      sha256 "2a0e8cdc70c51e8e49af54e5e1a366b654376f7f673e2804f1c35ac0b31231ad"

      define_method(:install) do
        bin.install "pop"
        bash_completion.install "completions/pop.bash" => "pop"
        zsh_completion.install "completions/pop.zsh" => "_pop"
        fish_completion.install "completions/pop.fish"
        man1.install "manpages/pop.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/pop/releases/download/v0.5.0/pop_0.5.0_Linux_x86_64.tar.gz"
      sha256 "5017aad5378fede81c5879e4205f869a5a94841df3b65649c0248ab1a6a3d536"
      define_method(:install) do
        bin.install "pop"
        bash_completion.install "completions/pop.bash" => "pop"
        zsh_completion.install "completions/pop.zsh" => "_pop"
        fish_completion.install "completions/pop.fish"
        man1.install "manpages/pop.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/pop/releases/download/v0.5.0/pop_0.5.0_Linux_armv7.tar.gz"
      sha256 "a93003eff88b8abdc2cd54597002db11b40afe0f935276f7ac57b0f6d9b29aeb"
      define_method(:install) do
        bin.install "pop"
        bash_completion.install "completions/pop.bash" => "pop"
        zsh_completion.install "completions/pop.zsh" => "_pop"
        fish_completion.install "completions/pop.fish"
        man1.install "manpages/pop.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/pop/releases/download/v0.5.0/pop_0.5.0_Linux_arm64.tar.gz"
      sha256 "79a4785d48548974a225ad44f160de447e627ba9291e973341c5fcb9fd96e0f5"
      define_method(:install) do
        bin.install "pop"
        bash_completion.install "completions/pop.bash" => "pop"
        zsh_completion.install "completions/pop.zsh" => "_pop"
        fish_completion.install "completions/pop.fish"
        man1.install "manpages/pop.1.gz"
      end
    end
  end
end
