# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sequin < Formula
  desc "Human-readable ANSI sequences."
  homepage "https://charm.sh/"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/charmbracelet/sequin/releases/download/v0.1.0/sequin_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "a568d49debec2511fd171910c570ac701ccddbe0336cbe93fa459a64a2570fb8"

      def install
        bin.install "sequin"
      end
    end
    on_arm do
      url "https://github.com/charmbracelet/sequin/releases/download/v0.1.0/sequin_0.1.0_Darwin_arm64.tar.gz"
      sha256 "0bb0e7cbc0aedb9eeb1c84cb8811528f6165b1cfa9e72cdf2f2b82b9467891d2"

      def install
        bin.install "sequin"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/sequin/releases/download/v0.1.0/sequin_0.1.0_Linux_x86_64.tar.gz"
        sha256 "98fb6c140aef2b8abd97549e6208c8a3968b0ce0ac62cfeb5e258f43f8c62151"

        def install
          bin.install "sequin"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/charmbracelet/sequin/releases/download/v0.1.0/sequin_0.1.0_Linux_arm64.tar.gz"
        sha256 "b2cc54b3b680785a7cc569f722af0b2255ff4aeececdd92c8940c8da624fa08c"

        def install
          bin.install "sequin"
        end
      end
    end
  end
end
