# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skate < Formula
  desc "A personal key value store"
  homepage "https://charm.sh/"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/skate/releases/download/v0.1.1/skate_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "1f084a6f241962dd71b15ad3d226efe616ecbb61172d6b33248da96f2f0414e1"

      def install
        bin.install "skate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/skate/releases/download/v0.1.1/skate_0.1.1_Darwin_arm64.tar.gz"
      sha256 "40dea73622ea6e458c9c534d7e984e435b37e28fb5932dd1c5eb41198936cd56"

      def install
        bin.install "skate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/skate/releases/download/v0.1.1/skate_0.1.1_linux_x86_64.tar.gz"
      sha256 "8058a6bbf0e81afcb0a89cb9d5eca8387be3ccbe1dfc2bb5b4d99cbebdd47863"

      def install
        bin.install "skate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/skate/releases/download/v0.1.1/skate_0.1.1_linux_arm64.tar.gz"
      sha256 "1469b7e4f1aa6d51a7b85337b89d9417f4ca7421dd661a6bd4d7d0f84e00ac9f"

      def install
        bin.install "skate"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/skate/releases/download/v0.1.1/skate_0.1.1_linux_armv6.tar.gz"
      sha256 "a4759cf3616efe127002d71a497eb50df6389747a1a18285b17f37f97b2e8079"

      def install
        bin.install "skate"
      end
    end
  end
end
