# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skate < Formula
  desc "A personal key value store 🛼"
  homepage "https://charm.sh/"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/skate/releases/download/v0.1.5/skate_0.1.5_Darwin_x86_64.tar.gz"
      sha256 "38fdd206aaea1031042f5334753dfcfbe9db3dc492f5a8fc61b279093c7279be"

      def install
        bin.install "skate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/skate/releases/download/v0.1.5/skate_0.1.5_Darwin_arm64.tar.gz"
      sha256 "85951de1e49b04847164035f802fd9b015bb9bed9a91bea690c1e2f522facaf7"

      def install
        bin.install "skate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/skate/releases/download/v0.1.5/skate_0.1.5_linux_arm64.tar.gz"
      sha256 "d5fbb0fdbc4b4d5d89394076fa11c3e2fe4dcd1728ff73c60ba1e6d9420127ed"

      def install
        bin.install "skate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/skate/releases/download/v0.1.5/skate_0.1.5_linux_x86_64.tar.gz"
      sha256 "8ccc8e57dc9003306edfc800f449dc455bc4eaa8a0a7cf5c1532d8969eb66226"

      def install
        bin.install "skate"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/skate/releases/download/v0.1.5/skate_0.1.5_linux_armv6.tar.gz"
      sha256 "c1dd431e9960466acaa500357b80d9bd6785d511e33d7a334e75115222e45738"

      def install
        bin.install "skate"
      end
    end
  end
end
