# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SoftServe < Formula
  desc "A tasty, self-hostable Git server for the command line🍦"
  homepage "https://charm.sh/"
  version "0.5.2"

  depends_on "git"
  depends_on "bash"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/soft-serve/releases/download/v0.5.2/soft-serve_Darwin_arm64.tar.gz"
      sha256 "43755d5599f61a079164dcb345e284d8711d453c40ca4d16116df60306cf8b89"

      def install
        bin.install "soft"
        bash_completion.install "completions/soft-serve.bash" => "soft-serve"
        zsh_completion.install "completions/soft-serve.zsh" => "_soft-serve"
        fish_completion.install "completions/soft-serve.fish"
        man1.install "manpages/soft-serve.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/soft-serve/releases/download/v0.5.2/soft-serve_Darwin_x86_64.tar.gz"
      sha256 "944d356de1c0f79716102eae80f399417f0b3b4bc8b3f4ef28550ccfd79f2828"

      def install
        bin.install "soft"
        bash_completion.install "completions/soft-serve.bash" => "soft-serve"
        zsh_completion.install "completions/soft-serve.zsh" => "_soft-serve"
        fish_completion.install "completions/soft-serve.fish"
        man1.install "manpages/soft-serve.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/soft-serve/releases/download/v0.5.2/soft-serve_Linux_arm64.tar.gz"
      sha256 "16951b8c6d7a99738f351194ec4e398ab1ff1f0fc53650d94bf6b2ed715c3bc9"

      def install
        bin.install "soft"
        bash_completion.install "completions/soft-serve.bash" => "soft-serve"
        zsh_completion.install "completions/soft-serve.zsh" => "_soft-serve"
        fish_completion.install "completions/soft-serve.fish"
        man1.install "manpages/soft-serve.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/soft-serve/releases/download/v0.5.2/soft-serve_Linux_x86_64.tar.gz"
      sha256 "333ce0369ad2776d358bbfe01125eaa52d34f794b023dafa620303632ef6aa21"

      def install
        bin.install "soft"
        bash_completion.install "completions/soft-serve.bash" => "soft-serve"
        zsh_completion.install "completions/soft-serve.zsh" => "_soft-serve"
        fish_completion.install "completions/soft-serve.fish"
        man1.install "manpages/soft-serve.1.gz"
      end
    end
  end
end
