# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SoftServe < Formula
  desc "A tasty, self-hostable Git server for the command line🍦"
  homepage "https://charm.sh/"
  version "0.4.3"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/soft-serve/releases/download/v0.4.3/soft-serve_0.4.3_Darwin_x86_64.tar.gz"
      sha256 "9fc25d835767d7b44dd39b2a319bf6df6a22bbdd9de486d6a4d642c96ca7479d"

      def install
        bin.install "soft"
        bash_completion.install "completions/soft-serve.bash" => "soft-serve"
        zsh_completion.install "completions/soft-serve.zsh" => "_soft-serve"
        fish_completion.install "completions/soft-serve.fish"
        man1.install "manpages/soft-serve.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/soft-serve/releases/download/v0.4.3/soft-serve_0.4.3_Darwin_arm64.tar.gz"
      sha256 "194512a14e3f90c6a9b393a74241c24886c5c1f71168d234c2b9d2e52d199399"

      def install
        bin.install "soft"
        bash_completion.install "completions/soft-serve.bash" => "soft-serve"
        zsh_completion.install "completions/soft-serve.zsh" => "_soft-serve"
        fish_completion.install "completions/soft-serve.fish"
        man1.install "manpages/soft-serve.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/soft-serve/releases/download/v0.4.3/soft-serve_0.4.3_Linux_arm64.tar.gz"
      sha256 "597818ed2015d3fd43674bde5d8ba6276a8b3db16c88973dec5c9e15e7be3483"

      def install
        bin.install "soft"
        bash_completion.install "completions/soft-serve.bash" => "soft-serve"
        zsh_completion.install "completions/soft-serve.zsh" => "_soft-serve"
        fish_completion.install "completions/soft-serve.fish"
        man1.install "manpages/soft-serve.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/soft-serve/releases/download/v0.4.3/soft-serve_0.4.3_Linux_x86_64.tar.gz"
      sha256 "f76d241936f2dcf14563aeacefc6a8276cf5d81ffb4f7338238b08f05e533ee9"

      def install
        bin.install "soft"
        bash_completion.install "completions/soft-serve.bash" => "soft-serve"
        zsh_completion.install "completions/soft-serve.zsh" => "_soft-serve"
        fish_completion.install "completions/soft-serve.fish"
        man1.install "manpages/soft-serve.1.gz"
      end
    end
  end
end
