# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SoftServe < Formula
  desc "A personal key value store"
  homepage "https://charm.sh/"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/soft-serve/releases/download/v0.1.2/soft-serve_0.1.2_Darwin_arm64.tar.gz"
      sha256 "f3716254cc85f474bdd467f42328571455abb9d25e41bba394c70ac92941e195"

      def install
        bin.install "soft"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/soft-serve/releases/download/v0.1.2/soft-serve_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "bedfdb0b0cb491178806385253ef12a5cb400a4398e6900c8e87edbdb8b5eac9"

      def install
        bin.install "soft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/soft-serve/releases/download/v0.1.2/soft-serve_0.1.2_linux_armv6.tar.gz"
      sha256 "6b0aa44637c9903c48279b59fec75d0a49621b95b68dffc5ed1c5c1c68271002"

      def install
        bin.install "soft"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/soft-serve/releases/download/v0.1.2/soft-serve_0.1.2_linux_x86_64.tar.gz"
      sha256 "15d7a49b99706721eb1b6af1a1be7a437600cc14934c2889799a53fa32622cfc"

      def install
        bin.install "soft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/soft-serve/releases/download/v0.1.2/soft-serve_0.1.2_linux_arm64.tar.gz"
      sha256 "6d081817427cdeef3eca6227ba03bf2e971cedc9258278c8e25f2c6dcc75596d"

      def install
        bin.install "soft"
      end
    end
  end
end
