# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vhs < Formula
  desc "A tool for recording terminal GIFs"
  homepage "https://charm.sh/"
  version "0.10.0"

  depends_on "ffmpeg"
  depends_on "ttyd"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/vhs/releases/download/v0.10.0/vhs_0.10.0_Darwin_x86_64.tar.gz"
      sha256 "0ef1ae1f399dc837204aa737d375a44cddb0a605be3c32eaa659d4e6a5ad0b70"

      def install
        bin.install "vhs"
        bash_completion.install "completions/vhs.bash" => "vhs"
        zsh_completion.install "completions/vhs.zsh" => "_vhs"
        fish_completion.install "completions/vhs.fish"
        man1.install "manpages/vhs.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/vhs/releases/download/v0.10.0/vhs_0.10.0_Darwin_arm64.tar.gz"
      sha256 "dc256c403305ac8ba623563d0ef3241a38024f35b27c705f79d523e9da618012"

      def install
        bin.install "vhs"
        bash_completion.install "completions/vhs.bash" => "vhs"
        zsh_completion.install "completions/vhs.zsh" => "_vhs"
        fish_completion.install "completions/vhs.fish"
        man1.install "manpages/vhs.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/vhs/releases/download/v0.10.0/vhs_0.10.0_Linux_x86_64.tar.gz"
      sha256 "b552c3870aca101dcafe533cfef32dceb7b783400ad32642e728775c9f125407"
      def install
        bin.install "vhs"
        bash_completion.install "completions/vhs.bash" => "vhs"
        zsh_completion.install "completions/vhs.zsh" => "_vhs"
        fish_completion.install "completions/vhs.fish"
        man1.install "manpages/vhs.1.gz"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/vhs/releases/download/v0.10.0/vhs_0.10.0_Linux_arm64.tar.gz"
      sha256 "6d7300028d4641b9dc004a05cf411d40f1e12e560cc6fca985dd90504b6652a7"
      def install
        bin.install "vhs"
        bash_completion.install "completions/vhs.bash" => "vhs"
        zsh_completion.install "completions/vhs.zsh" => "_vhs"
        fish_completion.install "completions/vhs.fish"
        man1.install "manpages/vhs.1.gz"
      end
    end
  end
end
