# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vhs < Formula
  desc "A tool for recording terminal GIFs"
  homepage "https://charm.sh/"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/vhs/releases/download/v0.1.0/vhs_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "a2f7e9dc2abb60d79bf2400a6e92dce76c3ffd9fb28f0ef32e23be7b38b83da4"

      def install
        bin.install "vhs"
        bash_completion.install "completions/vhs.bash" => "vhs"
        zsh_completion.install "completions/vhs.zsh" => "_vhs"
        fish_completion.install "completions/vhs.fish"
        man1.install "manpages/vhs.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/vhs/releases/download/v0.1.0/vhs_0.1.0_Darwin_arm64.tar.gz"
      sha256 "5e662368f60b0ec6e2fd439d70764637d165318cdf0c38b28e27292644cccc17"

      def install
        bin.install "vhs"
        bash_completion.install "completions/vhs.bash" => "vhs"
        zsh_completion.install "completions/vhs.zsh" => "_vhs"
        fish_completion.install "completions/vhs.fish"
        man1.install "manpages/vhs.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/vhs/releases/download/v0.1.0/vhs_0.1.0_Linux_x86_64.tar.gz"
      sha256 "414248bcb15a8315761ba7d33e87a24dfeccf4ac3d8825037f51f9b2a63545ed"

      def install
        bin.install "vhs"
        bash_completion.install "completions/vhs.bash" => "vhs"
        zsh_completion.install "completions/vhs.zsh" => "_vhs"
        fish_completion.install "completions/vhs.fish"
        man1.install "manpages/vhs.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/vhs/releases/download/v0.1.0/vhs_0.1.0_Linux_arm64.tar.gz"
      sha256 "c09e6bfc6f928b2998b743cf4904389900beee8eb0b42acdcb34df5923b98dd6"

      def install
        bin.install "vhs"
        bash_completion.install "completions/vhs.bash" => "vhs"
        zsh_completion.install "completions/vhs.zsh" => "_vhs"
        fish_completion.install "completions/vhs.fish"
        man1.install "manpages/vhs.1.gz"
      end
    end
  end
end
