# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vhs < Formula
  desc "A tool for recording terminal GIFs"
  homepage "https://charm.sh/"
  version "0.2.0"

  depends_on "ffmpeg"
  depends_on "ttyd"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/vhs/releases/download/v0.2.0/vhs_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "10b9f4bd24b4ae4ade114936e94715f172b767f9699ffdd1396fc361a97750bd"

      def install
        bin.install "vhs"
        bash_completion.install "completions/vhs.bash" => "vhs"
        zsh_completion.install "completions/vhs.zsh" => "_vhs"
        fish_completion.install "completions/vhs.fish"
        man1.install "manpages/vhs.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charmbracelet/vhs/releases/download/v0.2.0/vhs_0.2.0_Darwin_arm64.tar.gz"
      sha256 "673458aa55027d16068268020edb084f28c0727e38da938d782574d3fd077a8c"

      def install
        bin.install "vhs"
        bash_completion.install "completions/vhs.bash" => "vhs"
        zsh_completion.install "completions/vhs.zsh" => "_vhs"
        fish_completion.install "completions/vhs.fish"
        man1.install "manpages/vhs.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/charmbracelet/vhs/releases/download/v0.2.0/vhs_0.2.0_Linux_x86_64.tar.gz"
      sha256 "e5f339b7a65fd5b3de6f02e87aa71d50354a52e7253192d26eadc858597efb49"

      def install
        bin.install "vhs"
        bash_completion.install "completions/vhs.bash" => "vhs"
        zsh_completion.install "completions/vhs.zsh" => "_vhs"
        fish_completion.install "completions/vhs.fish"
        man1.install "manpages/vhs.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charmbracelet/vhs/releases/download/v0.2.0/vhs_0.2.0_Linux_arm64.tar.gz"
      sha256 "5fdc221389031b8a5a2efd2cf3b0e0d0c077a66f1f9acedab46d2cd62816c962"

      def install
        bin.install "vhs"
        bash_completion.install "completions/vhs.bash" => "vhs"
        zsh_completion.install "completions/vhs.zsh" => "_vhs"
        fish_completion.install "completions/vhs.fish"
        man1.install "manpages/vhs.1.gz"
      end
    end
  end
end
