# This file was generated by GoReleaser. DO NOT EDIT.
cask "crush" do
  desc "A powerful terminal-based AI assistant for developers, providing intelligent coding assistance directly in your terminal."
  homepage "https://charm.sh/crush"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crush"

  on_macos do
    on_intel do
      url "https://github.com/charmbracelet/crush/releases/download/v0.1.1/crush_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "6628644c4b15daf2d5a9c9253cb1b285cd13b50d46f535a7c9e5412aed94cbae"
    end
    on_arm do
      url "https://github.com/charmbracelet/crush/releases/download/v0.1.1/crush_0.1.1_Darwin_arm64.tar.gz"
      sha256 "5aff7e423554e5a87a2332b0b5419396574bc370a0a475692ee0adcc202e4c4f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/charmbracelet/crush/releases/download/v0.1.1/crush_0.1.1_Linux_x86_64.tar.gz"
      sha256 "f9969ddad399855bead1348e3cfda615e550db213d1899fd78add904a501c06f"
    end
    on_arm do
      url "https://github.com/charmbracelet/crush/releases/download/v0.1.1/crush_0.1.1_Linux_arm64.tar.gz"
      sha256 "2f215930030b273ff7ea83a538057a476d8c8e442ef31a3b32d3b70d535e526f"
    end
  end

  # No zap stanza required
end
