# This file was generated by GoReleaser. DO NOT EDIT.
cask "crush" do
  desc "A powerful terminal-based AI assistant for developers, providing intelligent coding assistance directly in your terminal."
  homepage "https://charm.sh/crush"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crush"

  on_macos do
    on_intel do
      url "https://github.com/charmbracelet/crush/releases/download/v0.1.2/crush_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "bacbeafe369bdc2f1b459d70c295e7716843395026b8c11d78bb69438d5284aa"
    end
    on_arm do
      url "https://github.com/charmbracelet/crush/releases/download/v0.1.2/crush_0.1.2_Darwin_arm64.tar.gz"
      sha256 "04eeee5dc9d14bc6868d155767ef628587e7e7a89f8ff37534ca6839b6085a56"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/charmbracelet/crush/releases/download/v0.1.2/crush_0.1.2_Linux_x86_64.tar.gz"
      sha256 "f962690ad58f2462314ca8ac959f16632c1003726045b40571397ceb41e4ca81"
    end
    on_arm do
      url "https://github.com/charmbracelet/crush/releases/download/v0.1.2/crush_0.1.2_Linux_arm64.tar.gz"
      sha256 "a8348be84f611e3ccce08b4eeb5103ede4f8c6e926ba5592e97c59199f13429f"
    end
  end

  # No zap stanza required
end
